name: "Block Webpage → main merges"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  block_webpage_into_main:
    runs-on: ubuntu-latest

    steps:
      - name: ⛔ Check for disallowed merge direction
        run: |
          echo "Base branch: ${{ github.event.pull_request.base.ref }}"
          echo "Head branch: ${{ github.event.pull_request.head.ref }}"
          if [[ "${{ github.event.pull_request.base.ref }}" == "main" && "${{ github.event.pull_request.head.ref }}" == "Webpage" ]]; then
            echo "::error ::Pull Requests from branch 'Webpage' to 'main' are blocked by policy."
            exit 1
          else
            echo "✅ PR merge direction is allowed."
          fi
