name: "Block Webpage → main merges"

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  block_webpage_into_main:
    # Only run when the PR’s base is 'main' and the head is exactly 'Webpage'
    if: >
      github.event.pull_request.base.ref == 'main' &&
      github.event.pull_request.head.ref == 'Webpage'
    runs-on: ubuntu-latest

    steps:
      - name: 🚫 Disallow merging Webpage into main
        run: |
          echo "::error ::Pull Requests from branch 'Webpage' to 'main' are blocked by policy."
          exit 1
